/* $Id$ */
package com.nasa.pictures.demo.di

import androidx.databinding.DataBindingComponent
import com.nasa.pictures.demo.util.ImageLoader
import javax.inject.Inject

/**
 * Created by Muthuraj on 20/03/21.
 *
 * The interface [DataBindingComponent] is generated by data binding compiler. It will have getter
 * methods for all classes that contains binding adapter method as an instance method. We need to
 * override those methods and provide instances for those classes so that data binding can access
 * those binding adapter methods.
 */
class AppDataBindingComponent @Inject constructor(private val imageLoader: ImageLoader) :
    DataBindingComponent {

    override fun getImageLoader(): ImageLoader {
        return imageLoader
    }
}